config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: :signup
  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  resources :users
  resources :sessions
  resources :groups
  resources :children

  root 'groups#index'

end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates_presence_of :number, :garden_number
  validates_uniqueness_of :number, scope: :garden_number

  has_many :memberships
  has_many :users, through: :memberships
  has_many :children
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email
  has_secure_password

  has_many :memberships
  has_many :groups, through: :memberships
  has_many :children
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authorize

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_url, alert: 'Ви не авторизовані!' unless current_user or controller_name == 'sessions' or controller_name == 'users'
  end

  helper_method :current_user
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  def new
  end

  def show
  end

  def edit
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path, notice: 'Нову групу створено.'
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def destroy
    @group = Group.find(params[:id])
  end

  private

  def group_params
    params.permit(:name, :number, :manager)
  end

end

app/controllers/sessions_controller.rb
# coding: utf-8
class SessionsController < ApplicationController
  def new
    render layout: 'auth'
  end

  def create
    user = User.find_by_email(params[:email])
    group = Group.find_by(number: params[:number], garden_number: params[:garden_number])
    if user && user.authenticate(params[:password]) && group
      unless group.memberships.find_by(user_id: user.id)
        group.memberships.create(user: user)
      end
      session[:user_id] = user.id
      flash.alert = 'Вхід успішний!'
      redirect_to group_path group
    else
      if group
        flash.now.alert = 'Email або пароль неправильні'
      else
        flash.now.alert = 'Не знайдено групу!'
      end
      render 'new', layout: 'auth'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: 'Ви вийшли!'
  end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  def new
    @user = User.new
    render layout: 'auth'
  end

  def create
    @user = User.new(user_params)
    if params[:number].blank? && params[:garden_number].blank?
      flash.alert = 'Вкажіть номер групи та садочка'
      render 'new', layout: 'auth'
    else
      @group = Group.find_by(number: params[:number], garden_number: params[:garden_number])
      if @user.save
        # binding.pry

        if @group
          @user.memberships.create(group: @group)
        else
          @group = Group.create(number: params[:number], garden_number: params[:garden_number])
          @user.memberships.create(group: @group, approved: true)
        end

        session[:user_id] = @user.id
        flash.alert = 'Дякуємо за реєстрацію!'
        redirect_to group_path @group
      else
        render 'new', layout: 'auth'
      end
    end

  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/children/edit.html.erb
<h1>Children#edit</h1>
<p>Find me in app/views/children/edit.html.erb</p>

app/views/children/new.html.erb
<h1>Children#new</h1>
<p>Find me in app/views/children/new.html.erb</p>

app/views/children/show.html.erb
<h1>Children#show</h1>
<p>Find me in app/views/children/show.html.erb</p>

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/index.html.erb
<h1>Перелік груп</h1>
<p>Групи до яких ви маєте доступ:</p>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Назва</th>
      <th>Садочок №</th>
      <th>Група №</th>
      <th>Керівник</th>
      <th>Кількість учасників</th>
      <th>Дата створення</th>
    </tr>
    </thead>
    <tbody>
    <% @groups.each do |g|%>
      <tr>
        <td><%= g.name || '---'%></td>
        <td><%= g.garden_number %></td>
        <td><%= link_to g.number, group_path(g) %></td>
        <td><%= g.manager || '---'%></td>
        <td><%= g.users.count %></td>
        <td><%= g.created_at.strftime('%d.%m.%Y') %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<p>Find me in app/views/groups/new.html.erb</p>

app/views/groups/show.html.erb
<% content_for :menu do %>
  група: <%= @group.number%> / садочок: <%= @group.garden_number%>
<% end %>

<h1>Група: <%= @group.number%></h1>
<h2>садочок: <%= @group.garden_number%></h2>
<p>Find me in app/views/groups/show.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <hr>
        <div>2015 &copy; O&V</div>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" title="Accounting System For Kindergardens">ASFK</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">
        <li class="pull-left">
          <a href><%= yield(:menu) if content_for?(:menu)%></a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Dashboard</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Help</a></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.email %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><%= link_to 'Вихід', logout_path, method: 'delete' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Реєстрація', signup_path%></li>
          <li><%= link_to 'Вхід', login_path%></li>
        <% end %>

      </ul>
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Пошук...">
      </form>


    </div>
  </div>
</nav>

<!--->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Asfk" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <%= render '/layouts/header' %>
    <% render '/layouts/footer' %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= bootstrap_flash %>
          <%= yield %>

          <!--<h1 class="page-header">Dashboard</h1>-->

          <!--<div class="row placeholders">-->
            <!--<div class="col-xs-6 col-sm-3 placeholder">-->
              <!--<img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjxnPjx0ZXh0IHg9Ijc0LjA0Njg3NSIgeT0iMTAwIiBzdHlsZT0iZmlsbDojRkZGRkZGO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L2c+PC9zdmc+" data-holder-rendered="true">-->
              <!--<h4>Label</h4>-->
              <!--<span class="text-muted">Something else</span>-->
            <!--</div>-->
            <!--<div class="col-xs-6 col-sm-3 placeholder">-->
              <!--<img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzM5REJBQyIvPjxnPjx0ZXh0IHg9Ijc0LjA0Njg3NSIgeT0iMTAwIiBzdHlsZT0iZmlsbDojMUUyOTJDO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L2c+PC9zdmc+" data-holder-rendered="true">-->
              <!--<h4>Label</h4>-->
              <!--<span class="text-muted">Something else</span>-->
            <!--</div>-->
            <!--<div class="col-xs-6 col-sm-3 placeholder">-->
              <!--<img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjxnPjx0ZXh0IHg9Ijc0LjA0Njg3NSIgeT0iMTAwIiBzdHlsZT0iZmlsbDojRkZGRkZGO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L2c+PC9zdmc+" data-holder-rendered="true">-->
              <!--<h4>Label</h4>-->
              <!--<span class="text-muted">Something else</span>-->
            <!--</div>-->
            <!--<div class="col-xs-6 col-sm-3 placeholder">-->
              <!--<img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="200x200" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzM5REJBQyIvPjxnPjx0ZXh0IHg9Ijc0LjA0Njg3NSIgeT0iMTAwIiBzdHlsZT0iZmlsbDojMUUyOTJDO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L2c+PC9zdmc+" data-holder-rendered="true">-->
              <!--<h4>Label</h4>-->
              <!--<span class="text-muted">Something else</span>-->
            <!--</div>-->
          <!--</div>-->

          <!--<h2 class="sub-header">Section title</h2>-->

        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Asfk" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body class="signin-body">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= bootstrap_flash %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user, html: {class: 'form-signin'} do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h4>Form is invalid</h4>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h2 class="form-signin-heading text-center">Реєстрація</h2>
  <%= f.text_field :email, class: 'form-control', placeholder: 'Email', type: 'email' %>
  <%= f.password_field :password, class: 'form-control', placeholder: 'Пароль', type: 'password' %>
  <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Пароль ще раз', type: 'password' %>
  <%= label_tag :number, 'Номер групи:'%>
  <%= number_field_tag(:number, params[:number], class: 'form-control') %><br/>
  <%= label_tag :garden_number, 'Номер садочка:'%>
  <%= number_field_tag(:garden_number, params[:garden_number], class: 'form-control') %><br/>
  <%= f.submit 'Зареєструватись', class: 'btn btn-lg btn-primary btn-block' %>

  <%= link_to 'Вхід', login_path, class: 'btn btn-lg btn-default btn-block' %>
<% end %>